### ISSUE TITLE
Generator removes $metadata from path

### ISSUE THREAD

**Issue by ulyssesb** [Soontao/c4codata#4]
Generator seems to remove $metadata from metadata query
```
> ./node_modules/c4codata/lib/cli/index.js -d true -m https://myxxxxx-api.s4hana.ondemand.com/sap/opu/odata/sap/API_PURCHASEREQ_PROCESS_SRV/$metadata -u USER -p "Password"
fetch metadata: https://myXXXXX-api.s4hana.ondemand.com/sap/opu/odata/sap/API_PURCHASEREQ_PROCESS_SRV/
Cannot read property 'edmx:DataServices' of undefined
TypeError: Cannot read property 'edmx:DataServices' of undefined
    at getEntityTypesDefault (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/generator/parser.js:43:29)
    at Object.parseMetaClassFromDefault (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/generator/parser.js:112:41)
    at Object.generateAllDefault (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/generator/generator.js:11:15)
    at generateAndWriteSingle (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/cli/index.js:89:40)
    at Object.<anonymous> (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/cli/index.js:117:21)
    at step (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/cli/index.js:44:23)
    at Object.next (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/cli/index.js:25:53)
    at fulfilled (/Users/ulysses/Code/projects/adb-safegate/contractreqtype/node_modules/c4codata/lib/cli/index.js:16:58)
```

Logging the fetch code /$metadata is not queried, thus not returned

**Comment by Soontao** [comment]
I'll reproduce it in the next work, but before that, please try to warp the metadata url with double quetes `"https://.../$metadata"`. 

Becaused some shell will think `$VAR` is try to replace string with environemnt variable `VAR`.

**Comment by Soontao** [comment]
Closed
